Upgrade to scalajs 1.7
scala-js/scala-js-cli pull request #35
Opened 2021-10-20 09:14 UTC by clutroth

2021-10-22 20:03 UTC, gzm0 requested changes
Only minor stuff.

2021-10-22 20:03 UTC, gzm0 commented on .github/workflows/ci.yml
> +        scalajsversion: ["1.7.0", "1.7.1"]
I do not quite understand how this is supposed to work: Won't we publish the CLI for a single Scala.js version only anyways? If so, what's the point of testing with an older one?

2021-10-22 20:03 UTC, gzm0 commented on project/build.properties
> +sbt.version=1.5.5
Put the sbt version upgrade into a separate commit to reduce noise?

2021-10-22 20:07 UTC, gzm0 commented
@clutroth thank you for your contributions to the CLI. I realize we have not even tagged a release after your last PR. Apologies for that.

@sjrd, I suggest we simply start releasing on its own versioning scheme? maybe with minor version bumps if we upgrade the minor Scala.js version? Definitely not the cleanest option, but better than not releasing at all :-/ WDYT?

2021-10-22 20:33 UTC, sjrd commented
Yes, probably that's what we should do.

Ideally I think we should explore something using [`cs install`](https://get-coursier.io/docs/cli-install#application-descriptors) so that we only have to release to Maven Central, and not deal with the native runner scripts.

2021-11-02 08:29 UTC, clutroth commented on .github/workflows/ci.yml
> +        scalajsversion: ["1.7.0", "1.7.1"]
You're right. It's pointless.

2021-11-02 08:29 UTC, clutroth commented on project/build.properties
> +sbt.version=1.5.5
done

2021-11-02 08:52 UTC, clutroth commented
Glad to help :) I'd appreciate release.

2021-11-02 19:55 UTC, gzm0 approved these changes

2021-11-02 20:01 UTC, merged