Tweaking
scala-js/scala-js-cli pull request #42
Opened 2022-03-21 16:29 UTC by alexarchambault

This PR allows users to specify a main method accepting no arguments, which is useful to use methods such as `org.scalajs.testing.bridge.Bridge.start` as an entrypoint.

Right now, arg-less entrypoints can be specified like `--mainMethod org.scalajs.testing.bridge.Bridge.start!` (`!` at the end of the method name), but let me know if you'd prefer those to be specified another way.

These changes are motivated by https://github.com/VirtusLab/scala-cli/pull/676, which runs the Scala.JS linker in an external process, rather than embedding it in the Scala CLI native image.

2022-03-21 16:45 UTC, sjrd reviewed
I guess the syntax is going to be subject to some bikeshedding. Using a symbol is annoying if it's not self-explanatory/intuitive. I would opt for a separate option name.

@gzm0 Any opinion?

2022-03-21 16:45 UTC, sjrd commented on .gitignore
> +.bsp/
I'm pretty sure this only happens at the top-level, so it should be
```suggestion
/.bsp/
```

2022-03-21 17:25 UTC, alexarchambault commented on .gitignore
> +.bsp/
Should be fixed.

2022-03-21 17:25 UTC, alexarchambault commented
Just changed the syntax to an option. That's `--mainMethodWithNoArgs org.scalajs.testing.bridge.Bridge.start` in the current state of the PR.

2022-03-23 09:30 UTC, sjrd requested changes

2022-03-23 09:30 UTC, sjrd commented on src/main/scala/org/scalajs/cli/Scalajsld.scala
> +        mainMethodsWithNoArgs.map(moduleInitializer(_, hasArgs = false))
This will change the order of module initializers, compared to what the user writes on the command-line, if they use both main methods with args and without args. We should keep a unique field `moduleInitializers: Seq[ModuleInitializer]`, and instead have the `.action { ... }` calls perform the conversion from string to `ModuleInitializer` to append to that unique list.

2022-03-23 10:08 UTC, alexarchambault commented on src/main/scala/org/scalajs/cli/Scalajsld.scala
> +        mainMethodsWithNoArgs.map(moduleInitializer(_, hasArgs = false))
Yep, should be fixed.

2022-03-23 10:16 UTC, sjrd approved these changes

2022-03-23 10:17 UTC, merged